name: Deploy to Heroku

on:
  push:
    branches:
      - main  # Déclencher le déploiement lorsque vous poussez sur la branche principale. Vous pouvez ajouter d'autres branches si nécessaire.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "myquizzz"
